FROM node:8
MAINTAINER SQUARE <square.jeon@gmail.com>

# 앱 디렉터리
WORKDIR /usr/src/dodamDID

# 기본 설치
RUN apt-get update
RUN apt-get install sudo
RUN apt-get install curl
RUN apt-get install apt-transport-https

# yarn 설치
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN sudo apt-get update && sudo apt-get -y install yarn

# 의존성 설치
COPY package.json package.json
RUN yarn

# 소스 추가
COPY . .

# 포트 바인딩
EXPOSE 5000

# 런타임 정의
RUN echo "yarn start" > "dodamDID.sh"
RUN chmod 777 dodamDID.sh
CMD ./dodamDID.sh